# config.yaml

max_new_tokens: 200
temperature: 0.7
top_k: 50
top_p: 0.9
repetition_penalty: 1.1

dataset_name: sentence-transformers/natural-questions
dataset_split: train[:1000]
dataset_path: /home/research/Desktop/Models

phi_model: /home/research/Desktop/Models/microsoft/phi-2
pythia_model: /home/research/Desktop/Models/EleutherAI/pythia-1b
refiner_model: /home/research/Desktop/Models/meta-llama/Llama-3.2-1B-Instruct
embedder_model: /home/research/Desktop/Models/sentence-transformers/all-MiniLM-L6-v2

